language: java
jdk: openjdk9
before_install:
  - wget http://services.gradle.org/distributions/gradle-5.5.1-bin.zip
  - unzip -qq gradle-5.5.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.5.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v  
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11  
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE "test-gem";' -U postgres
  - psql -c "CREATE ROLE gem SUPERUSER LOGIN CREATEDB PASSWORD 'gem';" -U postgres
services:
  - postgresql
addons:
  postgresql: "11.2"
script:
  - gradle clean
  - gradle test
  
